version: '3'

networks:
  cat-net:
    driver: bridge

services:

  server:
    image: iudx/cat-all:latest
    environment:
      - HOSTNAME=server
      - ZOOKEEPER=zookeeper
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./config.properties:/usr/share/app/config.properties
      - ./docs/:/usr/share/app/docs
      - ./keystore.jks:/usr/share/app/keystore.jks
    depends_on:
      - "zookeeper"
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

  dev:
    image: iudx/cat-dev:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./config.properties:/usr/share/app/config.properties
      - ./keystore.jks:/usr/share/app/keystore.jks
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - cat-net
