version: '3'

networks:
  cat-net:
    driver: bridge

services:

  server:
    image: iudx/cat-depl:latest
    environment:
      - HOSTNAME=server
      - ZOOKEEPER=zookeeper
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./docs/:/usr/share/app/docs
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    depends_on:
      - "zookeeper"
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  dev:
    image: iudx/cat-dev:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - cat-net
