version: '3.7'

networks:
  cat-net:
    driver: bridge

services:

  cat:
    image: ghcr.io/datakaveri/iudx-catalogue-server:prod
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=INFO
      - CAT_JAVA_OPTS=-Xmx4096m
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    depends_on:
      - "zookeeper"
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$CAT_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  dev:
    image: ghcr.io/datakaveri/iudx-catalogue-server:dev
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=DEBUG
      - CAT_JAVA_OPTS=-Xmx1024m
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command:  bash -c "exec java $$CAT_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  test:
    image: ghcr.io/datakaveri/iudx-catalogue-server:test
    environment:
      - CAT_URL=http://catalogue.iudx.io
      - WORKSPACE
      - LOG_LEVEL=DEBUG
    volumes:
      - /home/ubuntu/configs/cat-config-test.json:/usr/share/app/configs/config-test.json
      - ./src/:/usr/share/app/src
      - /home/ubuntu/configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - /home/ubuntu/configs/authkeystore.ks:/usr/share/app/configs/authkeystore.ks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
    command: bash -c "docker/runTests.sh && cp -r target /tmp/test"
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
        
  perfTest:
    image: ghcr.io/datakaveri/iudx-catalogue-server:test
    environment:
      - CAT_URL=http://catalogue.iudx.io
      - WORKSPACE
      - LOG_LEVEL=DEBUG
    volumes:
      - /home/ubuntu/configs/cat-config-test.json:/usr/share/app/configs/config-test.json
      - ./src/:/usr/share/app/src
      - /home/ubuntu/configs/authkeystore.ks:/usr/share/app/configs/authkeystore.ks
      - /home/ubuntu/configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
    ports:
      - "8444:8443"
    command: bash -c "mvn clean compile exec:java@catalogue-server"
    networks: 
      - cat-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"


  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - cat-net
